# Generated by Django 5.2 on 2025-04-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_location_profile_name_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
