# Generated by Django 5.2 on 2025-04-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
